In [3]:
import pandas as pd

data_2024 = pd.read_csv("data/NFL_2024_season_data.csv")
data_2024['year'] = 2024
data_2023 = pd.read_csv("data/NFL_2023_season_data.csv")
data_2023['year'] = 2023
data_2022 = pd.read_csv("data/NFL_2022_season_data.csv")
data_2022['year'] = 2022
data_2021 = pd.read_csv("data/NFL_2021_season_data.csv")
data_2021['year'] = 2021
data_2020 = pd.read_csv("data/NFL_2020_season_data.csv")
data_2020['year'] = 2020
data = pd.concat([data_2024, data_2023, data_2022, data_2021, data_2020])
data = data.drop(['2:00 PM', '2PP', 'FantPt', 'DKPt', 'FDPt', 'VBD', 'OvRank', '-9999', 'PPRâ–¼'], axis=1)
te_data = data[data['FantPos'] == 'TE']
te_data = te_data.reset_index()
te_data.columns

Index(['index', 'Rk', 'Player', 'Tm', 'FantPos', 'Age', 'G', 'GS', 'Cmp',
       'Passing Att', 'Passing Yds', 'Passing TD', 'Int', 'Rushing Att',
       'Rushing Yds', 'Rushing Y/A', 'Rushing TD', 'Tgt', 'Rec',
       'Receiving Yds', 'Receiving Y/R', 'Receiving TD', 'Fmb', 'FL',
       'Total TD', 'PPR', 'PosRank', 'year'],
      dtype='object')

In [4]:
te_data = te_data.drop(['index', 'Rk', 'FantPos', 'Cmp', 'Passing Att', 'Passing Yds', 'Passing TD', 'Int'], axis=1)
te_data['Player'] = te_data['Player'].str.replace('+', '', regex=False)
te_data['Player'] = te_data['Player'].str.replace('*', '', regex=False)
te_data.head()

,Player,Tm,Age,G,GS,Rushing Att,Rushing Yds,Rushing Y/A,Rushing TD,Tgt,Rec,Receiving Yds,Receiving Y/R,Receiving TD,Fmb,FL,Total TD,PPR,PosRank,year
0,George Kittle,SFO,31,15,15,0.0,0.0,NaN,0.0,94.0,78.0,1106.0,14.18,8.0,0.0,0.0,8,236.6,1,2024
1,Brock Bowers,LVR,22,17,16,5.0,13.0,2.60,0.0,153.0,112.0,1194.0,10.66,5.0,0.0,0.0,5,262.7,2,2024
2,Trey McBride,ARI,25,16,16,1.0,2.0,2.00,1.0,147.0,111.0,1146.0,10.32,2.0,0.0,0.0,4,249.8,3,2024
3,Jonnu Smith,MIA,29,17,6,2.0,-1.0,-0.50,0.0,111.0,88.0,884.0,10.05,8.0,2.0,1.0,8,222.3,4,2024
4,Mark Andrews,BAL,29,17,13,4.0,5.0,1.25,0.0,69.0,55.0,673.0,12.24,11.0,0.0,0.0,11,188.8,5,2024