In [453]:
import pandas as pd

data_2024 = pd.read_csv("data/NFL_2024_season_data.csv")
data_2024['year'] = 2024
data_2023 = pd.read_csv("data/NFL_2023_season_data.csv")
data_2023['year'] = 2023
data_2022 = pd.read_csv("data/NFL_2022_season_data.csv")
data_2022['year'] = 2022
data_2021 = pd.read_csv("data/NFL_2021_season_data.csv")
data_2021['year'] = 2021
data_2020 = pd.read_csv("data/NFL_2020_season_data.csv")
data_2020['year'] = 2020

In [454]:
data = pd.concat([data_2024, data_2023, data_2022, data_2021])
data.shape

(2605, 35)

In [455]:
data = data.drop(['2:00 PM', '2PP', 'FantPt', 'DKPt', 'FDPt', 'VBD', 'OvRank', '-9999'], axis=1)

In [456]:
wr_data = data[data['FantPos'] == 'WR']

In [457]:
wr_data = wr_data.reset_index()
wr_data.head()

,index,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Passing Att,...,Rec,Receiving Yds,Receiving Y/R,Receiving TD,Fmb,FL,Total TD,PPR,PosRank,year
0,4,5,Ja'Marr Chase*+,CIN,WR,24,17,16,0.0,0.0,...,127.0,1708.0,13.45,17.0,0.0,0.0,17,403.0,1,2024
1,11,12,Justin Jefferson*+,MIN,WR,25,17,17,1.0,1.0,...,103.0,1533.0,14.88,10.0,1.0,0.0,10,317.5,2,2024
2,17,18,Amon-Ra St. Brown*+,DET,WR,25,17,17,1.0,1.0,...,115.0,1263.0,10.98,12.0,1.0,1.0,12,316.2,3,2024
3,18,19,Brian Thomas*,JAX,WR,22,17,16,0.0,0.0,...,87.0,1282.0,14.74,10.0,0.0,0.0,10,284.0,4,2024
4,22,23,Terry McLaurin*,WAS,WR,29,17,17,0.0,0.0,...,82.0,1096.0,13.37,13.0,1.0,1.0,13,267.8,5,2024

In [458]:
wr_data.columns

Index(['index', 'Rk', 'Player', 'Tm', 'FantPos', 'Age', 'G', 'GS', 'Cmp',
       'Passing Att', 'Passing Yds', 'Passing TD', 'Int', 'Rushing Att',
       'Rushing Yds', 'Rushing Y/A', 'Rushing TD', 'Tgt', 'Rec',
       'Receiving Yds', 'Receiving Y/R', 'Receiving TD', 'Fmb', 'FL',
       'Total TD', 'PPR', 'PosRank', 'year'],
      dtype='object')

In [459]:
wr_data = wr_data.drop(['index', 'Rk', 'FantPos', 'Cmp', 'Passing Att', 'Passing Yds', 'Passing TD', 'Int'], axis=1)

In [460]:
wr_data.head()

,Player,Tm,Age,G,GS,Rushing Att,Rushing Yds,Rushing Y/A,Rushing TD,Tgt,Rec,Receiving Yds,Receiving Y/R,Receiving TD,Fmb,FL,Total TD,PPR,PosRank,year
0,Ja'Marr Chase*+,CIN,24,17,16,3.0,32.0,10.67,0.0,175.0,127.0,1708.0,13.45,17.0,0.0,0.0,17,403.0,1,2024
1,Justin Jefferson*+,MIN,25,17,17,1.0,3.0,3.00,0.0,154.0,103.0,1533.0,14.88,10.0,1.0,0.0,10,317.5,2,2024
2,Amon-Ra St. Brown*+,DET,25,17,17,2.0,6.0,3.00,0.0,141.0,115.0,1263.0,10.98,12.0,1.0,1.0,12,316.2,3,2024
3,Brian Thomas*,JAX,22,17,16,6.0,48.0,8.00,0.0,133.0,87.0,1282.0,14.74,10.0,0.0,0.0,10,284.0,4,2024
4,Terry McLaurin*,WAS,29,17,17,2.0,2.0,1.00,0.0,117.0,82.0,1096.0,13.37,13.0,1.0,1.0,13,267.8,5,2024

In [461]:
wr_data['Player'] = wr_data['Player'].str.replace('+', '', regex=False)
wr_data['Player'] = wr_data['Player'].str.replace('*', '', regex=False)
wr_data.head()

,Player,Tm,Age,G,GS,Rushing Att,Rushing Yds,Rushing Y/A,Rushing TD,Tgt,Rec,Receiving Yds,Receiving Y/R,Receiving TD,Fmb,FL,Total TD,PPR,PosRank,year
0,Ja'Marr Chase,CIN,24,17,16,3.0,32.0,10.67,0.0,175.0,127.0,1708.0,13.45,17.0,0.0,0.0,17,403.0,1,2024
1,Justin Jefferson,MIN,25,17,17,1.0,3.0,3.00,0.0,154.0,103.0,1533.0,14.88,10.0,1.0,0.0,10,317.5,2,2024
2,Amon-Ra St. Brown,DET,25,17,17,2.0,6.0,3.00,0.0,141.0,115.0,1263.0,10.98,12.0,1.0,1.0,12,316.2,3,2024
3,Brian Thomas,JAX,22,17,16,6.0,48.0,8.00,0.0,133.0,87.0,1282.0,14.74,10.0,0.0,0.0,10,284.0,4,2024
4,Terry McLaurin,WAS,29,17,17,2.0,2.0,1.00,0.0,117.0,82.0,1096.0,13.37,13.0,1.0,1.0,13,267.8,5,2024

In [462]:
wr_data[wr_data['year'] == 2020]

Empty DataFrame
Columns: [Player, Tm, Age, G, GS, Rushing Att, Rushing Yds, Rushing Y/A, Rushing TD, Tgt, Rec, Receiving Yds, Receiving Y/R, Receiving TD, Fmb, FL, Total TD, PPR, PosRank, year]
Index: []

In [463]:
wr_data[wr_data.isna().any(axis=1)]

,Player,Tm,Age,G,GS,Rushing Att,Rushing Yds,Rushing Y/A,Rushing TD,Tgt,Rec,Receiving Yds,Receiving Y/R,Receiving TD,Fmb,FL,Total TD,PPR,PosRank,year
6,Mike Evans,TAM,31,14,14,0.0,0.0,NaN,0.0,110.0,74.0,1004.0,13.57,11.0,0.0,0.0,11,240.4,7,2024
9,Courtland Sutton,DEN,29,17,13,0.0,0.0,NaN,0.0,135.0,81.0,1081.0,13.35,8.0,1.0,1.0,8,240.3,10,2024
10,Ladd McConkey,LAC,23,16,14,0.0,0.0,NaN,0.0,112.0,82.0,1149.0,14.01,7.0,2.0,0.0,7,240.9,11,2024
11,Davante Adams,2TM,32,14,14,0.0,0.0,NaN,0.0,141.0,85.0,1063.0,12.51,8.0,0.0,0.0,8,241.3,12,2024
14,Jerry Jeudy,CLE,25,17,16,0.0,0.0,NaN,0.0,145.0,90.0,1229.0,13.66,4.0,0.0,0.0,4,240.9,15,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018,Racey McMath,TEN,22,9,0,0.0,0.0,NaN,0.0,6.0,2.0,8.0,4.00,0.0,1.0,1.0,0,0.8,271,2021
1019,Malik Taylor,GNB,26,10,0,0.0,0.0,NaN,0.0,3.0,2.0,14.0,7.00,0.0,1.0,1.0,0,1.4,270,2021
1020,Travis Benjamin,SFO,32,10,0,0.0,0.0,NaN,0.0,5.0,0.0,0.0,NaN,0.0,1.0,1.0,0,-2.0,272,2021
1021,J.J. Koski,LAR,25,5,0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,1.0,1.0,0,-2.0,273,2021
1022,Diontae Spencer,DEN,29,15,0,0.0,0.0,NaN,0.0,4.0,1.0,-3.0,-3.00,0.0,2.0,2.0,0,-3.3,274,2021

In [464]:
wr_data = wr_data.fillna(0.0)
wr_data[wr_data.isna().any(axis=1)]

Empty DataFrame
Columns: [Player, Tm, Age, G, GS, Rushing Att, Rushing Yds, Rushing Y/A, Rushing TD, Tgt, Rec, Receiving Yds, Receiving Y/R, Receiving TD, Fmb, FL, Total TD, PPR, PosRank, year]
Index: []

In [465]:
wr_data['PPG'] = wr_data['PPR']/wr_data['G']

In [466]:
training = wr_data[wr_data['year'] != 2024]
predicting = wr_data[(wr_data['year'] == 2024) | (wr_data['year'] == 2023)]

In [467]:
evans = training[training['Player'] == 'Mike Evans']
evans = evans.reset_index()
for row in evans.itertuples():
    print(row)
    break

Pandas(Index=0, index=254, Player='Mike Evans', Tm='TAM', Age=30, G=17, GS=17, _7=0.0, _8=0.0, _9=0.0, _10=0.0, Tgt=136.0, Rec=79.0, _13=1255.0, _14=15.89, _15=13.0, Fmb=0.0, FL=0.0, _18=13, PPR=282.5, PosRank=4, year=2023, PPG=16.61764705882353)

In [468]:
evans.columns

Index(['index', 'Player', 'Tm', 'Age', 'G', 'GS', 'Rushing Att', 'Rushing Yds',
       'Rushing Y/A', 'Rushing TD', 'Tgt', 'Rec', 'Receiving Yds',
       'Receiving Y/R', 'Receiving TD', 'Fmb', 'FL', 'Total TD', 'PPR',
       'PosRank', 'year', 'PPG'],
      dtype='object')

In [469]:
final_cols = ['Player', 'Age', 
              '0_ago_G', '0_ago_GS', '0_ago_RushingAtt', '0_ago_RushingYds', '0_ago_RushingY/A', '0_ago_RushingTD', '0_ago_Tgt', '0_ago_Rec', '0_ago_ReceivingYds', 
              '0_ago_ReceivingY/R', '0_ago_ReceivingTD', '0_ago_Fmb', '0_ago_FL', '0_ago_TotalTD', '0_ago_PPR', '0_ago_PosRank', '0_ago_year', '0_ago_PPG',
              '1_ago_G', '1_ago_GS', '1_ago_RushingAtt', '1_ago_RushingYds', '1_ago_RushingY/A', '1_ago_RushingTD', '1_ago_Tgt', '1_ago_Rec', '1_ago_ReceivingYds', 
              '1_ago_ReceivingY/R', '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL', '1_ago_TotalTD', '1_ago_PPR', '1_ago_PosRank', '1_ago_year', '1_ago_PPG',
              '2_ago_G', '2_ago_GS', '2_ago_RushingAtt', '2_ago_RushingYds', '2_ago_RushingY/A', '2_ago_RushingTD', '2_ago_Tgt', '2_ago_Rec', '2_ago_ReceivingYds', 
              '2_ago_ReceivingY/R', '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL', '2_ago_TotalTD', '2_ago_PPR', '2_ago_PosRank', '2_ago_year', '2_ago_PPG'
              ]
wr = pd.DataFrame(columns=final_cols, index=[0])
wr = wr.fillna(0.0)
for player in training["Player"].unique():
    individual = training[training['Player'] == player]
    individual = individual.reset_index()
    data = pd.DataFrame(columns=final_cols, index=[0])
    data['Player'] = player
    data['Age'] = individual.loc[0]['Age']
    for row in individual.itertuples():
        data[str(2023 - row.year) + '_ago_G'] = row.G
        data[str(2023 - row.year) + '_ago_GS'] = row.GS
        data[str(2023 - row.year) + '_ago_RushingAtt'] = row._7
        data[str(2023 - row.year) + '_ago_RushingYds'] = row._8
        data[str(2023 - row.year) + '_ago_RushingY/A'] = row._9
        data[str(2023 - row.year) + '_ago_RushingTD'] = row._10
        data[str(2023 - row.year) + '_ago_Tgt'] = row.Tgt
        data[str(2023 - row.year) + '_ago_Rec'] = row.Rec
        data[str(2023 - row.year) + '_ago_ReceivingYds'] = row._13
        data[str(2023 - row.year) + '_ago_ReceivingY/R'] = row._14
        data[str(2023 - row.year) + '_ago_ReceivingTD'] = row._15
        data[str(2023 - row.year) + '_ago_Fmb'] = row.Fmb
        data[str(2023 - row.year) + '_ago_FL'] = row.FL
        data[str(2023 - row.year) + '_ago_TotalTD'] = row._18
        data[str(2023 - row.year) + '_ago_PPR'] = row.PPR
        data[str(2023 - row.year) + '_ago_PosRank'] = row.PosRank
        data[str(2023 - row.year) + '_ago_PPG'] = row.PPG

    wr = pd.concat([wr, data])

wr.head()

/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  wr = wr.fillna(0.0)
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/3076309150.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr = pd.concat([wr, data])

,Player,Age,0_ago_G,0_ago_GS,0_ago_RushingAtt,0_ago_RushingYds,0_ago_RushingY/A,0_ago_RushingTD,0_ago_Tgt,0_ago_Rec,...,2_ago_ReceivingYds,2_ago_ReceivingY/R,2_ago_ReceivingTD,2_ago_Fmb,2_ago_FL,2_ago_TotalTD,2_ago_PPR,2_ago_PosRank,2_ago_year,2_ago_PPG
0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
0,CeeDee Lamb,24.0,17.0,17.0,14.0,113.0,8.07,2.0,181.0,135.0,...,1102.0,13.95,6.0,0.0,0.0,6.0,232.8,14.0,NaN,14.550000
0,Tyreek Hill,29.0,16.0,16.0,6.0,15.0,2.50,0.0,171.0,119.0,...,1239.0,11.16,9.0,2.0,1.0,9.0,296.5,7.0,NaN,17.441176
0,Amon-Ra St. Brown,24.0,16.0,16.0,4.0,24.0,6.00,0.0,164.0,119.0,...,912.0,10.13,5.0,0.0,0.0,6.0,227.3,23.0,NaN,13.370588
0,Mike Evans,30.0,17.0,17.0,0.0,0.0,0.00,0.0,136.0,79.0,...,1035.0,13.99,14.0,0.0,0.0,14.0,262.5,6.0,NaN,16.406250

In [470]:
wr = wr.iloc[1:]
wr.head()

,Player,Age,0_ago_G,0_ago_GS,0_ago_RushingAtt,0_ago_RushingYds,0_ago_RushingY/A,0_ago_RushingTD,0_ago_Tgt,0_ago_Rec,...,2_ago_ReceivingYds,2_ago_ReceivingY/R,2_ago_ReceivingTD,2_ago_Fmb,2_ago_FL,2_ago_TotalTD,2_ago_PPR,2_ago_PosRank,2_ago_year,2_ago_PPG
0,CeeDee Lamb,24.0,17.0,17.0,14.0,113.0,8.07,2.0,181.0,135.0,...,1102.0,13.95,6.0,0.0,0.0,6.0,232.8,14.0,NaN,14.550000
0,Tyreek Hill,29.0,16.0,16.0,6.0,15.0,2.50,0.0,171.0,119.0,...,1239.0,11.16,9.0,2.0,1.0,9.0,296.5,7.0,NaN,17.441176
0,Amon-Ra St. Brown,24.0,16.0,16.0,4.0,24.0,6.00,0.0,164.0,119.0,...,912.0,10.13,5.0,0.0,0.0,6.0,227.3,23.0,NaN,13.370588
0,Mike Evans,30.0,17.0,17.0,0.0,0.0,0.00,0.0,136.0,79.0,...,1035.0,13.99,14.0,0.0,0.0,14.0,262.5,6.0,NaN,16.406250
0,Puka Nacua,22.0,17.0,17.0,12.0,89.0,7.42,0.0,160.0,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [471]:
wr = wr.fillna(0.0)
wr.columns

Index(['Player', 'Age', '0_ago_G', '0_ago_GS', '0_ago_RushingAtt',
       '0_ago_RushingYds', '0_ago_RushingY/A', '0_ago_RushingTD', '0_ago_Tgt',
       '0_ago_Rec', '0_ago_ReceivingYds', '0_ago_ReceivingY/R',
       '0_ago_ReceivingTD', '0_ago_Fmb', '0_ago_FL', '0_ago_TotalTD',
       '0_ago_PPR', '0_ago_PosRank', '0_ago_year', '0_ago_PPG', '1_ago_G',
       '1_ago_GS', '1_ago_RushingAtt', '1_ago_RushingYds', '1_ago_RushingY/A',
       '1_ago_RushingTD', '1_ago_Tgt', '1_ago_Rec', '1_ago_ReceivingYds',
       '1_ago_ReceivingY/R', '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL',
       '1_ago_TotalTD', '1_ago_PPR', '1_ago_PosRank', '1_ago_year',
       '1_ago_PPG', '2_ago_G', '2_ago_GS', '2_ago_RushingAtt',
       '2_ago_RushingYds', '2_ago_RushingY/A', '2_ago_RushingTD', '2_ago_Tgt',
       '2_ago_Rec', '2_ago_ReceivingYds', '2_ago_ReceivingY/R',
       '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL', '2_ago_TotalTD',
       '2_ago_PPR', '2_ago_PosRank', '2_ago_year', '2_ago_PPG'],
      dtype='object')

In [472]:
wr = wr.drop(['0_ago_G', '0_ago_GS', '0_ago_RushingAtt',
       '0_ago_RushingYds', '0_ago_RushingY/A', '0_ago_RushingTD', '0_ago_Tgt',
       '0_ago_Rec', '0_ago_ReceivingYds', '0_ago_ReceivingY/R',
       '0_ago_ReceivingTD', '0_ago_Fmb', '0_ago_FL', '0_ago_TotalTD',
       '0_ago_PosRank', '0_ago_year', '0_ago_PPG'], axis=1)

wr.columns

Index(['Player', 'Age', '0_ago_PPR', '1_ago_G', '1_ago_GS', '1_ago_RushingAtt',
       '1_ago_RushingYds', '1_ago_RushingY/A', '1_ago_RushingTD', '1_ago_Tgt',
       '1_ago_Rec', '1_ago_ReceivingYds', '1_ago_ReceivingY/R',
       '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL', '1_ago_TotalTD',
       '1_ago_PPR', '1_ago_PosRank', '1_ago_year', '1_ago_PPG', '2_ago_G',
       '2_ago_GS', '2_ago_RushingAtt', '2_ago_RushingYds', '2_ago_RushingY/A',
       '2_ago_RushingTD', '2_ago_Tgt', '2_ago_Rec', '2_ago_ReceivingYds',
       '2_ago_ReceivingY/R', '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL',
       '2_ago_TotalTD', '2_ago_PPR', '2_ago_PosRank', '2_ago_year',
       '2_ago_PPG'],
      dtype='object')

In [473]:
from sklearn.model_selection import train_test_split

X = wr.drop(['0_ago_PPR', 'Player'], axis=1)
y = wr[['Player', '0_ago_PPR']]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=0)

In [474]:
# simplified_X = wr[['Age', '1_ago_GS', '1_ago_PosRank', '1_ago_PPG', '1_ago_PPR', '2_ago_GS', '2_ago_PosRank', '2_ago_PPG', '2_ago_PPR']]
simplified_X = wr[['Age', '1_ago_PPG', '1_ago_PPR', '2_ago_PPG', '2_ago_PPR']]
simplified_y = wr[['Player', '0_ago_PPR']]
simplified_X_train, simplified_X_test, simplified_y_train, simplified_y_test = train_test_split(simplified_X, simplified_y, train_size=0.75, random_state=0)

In [475]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=0)
model.fit(simplified_X_train, simplified_y_train['0_ago_PPR'])
model.score(simplified_X_test, simplified_y_test['0_ago_PPR'])

0.6732159005278648

In [476]:
y_pred = model.predict(simplified_X_test)

In [477]:
y_test = y_test.reset_index()

In [478]:
y_test

    index           Player  0_ago_PPR
0       0       Jeff Smith        0.0
1       0  Henry Ruggs III        0.0
2       0     Jalen Guyton       24.9
3       0         DJ Chark      115.5
4       0      Frank Darby        0.0
..    ...              ...        ...
92      0     Dante Pettis        0.0
93      0    Dezmon Patmon        0.0
94      0   Rashod Bateman       76.5
95      0      Keke Coutee        0.0
96      0    DeVonta Smith      227.6

[97 rows x 3 columns]

In [479]:
y_test = y_test.drop(['index'], axis=1)
y_test

             Player  0_ago_PPR
0        Jeff Smith        0.0
1   Henry Ruggs III        0.0
2      Jalen Guyton       24.9
3          DJ Chark      115.5
4       Frank Darby        0.0
..              ...        ...
92     Dante Pettis        0.0
93    Dezmon Patmon        0.0
94   Rashod Bateman       76.5
95      Keke Coutee        0.0
96    DeVonta Smith      227.6

[97 rows x 2 columns]

In [480]:
y_pred = pd.Series(y_pred)
y_pred

0      11.672000
1      17.511931
2      12.468000
3      40.352000
4       1.125867
         ...
92     28.266000
93     15.213000
94     37.998000
95      1.631010
96    248.901000
Length: 97, dtype: float64

In [481]:
comp = pd.concat([y_test, y_pred], axis=1)
comp

             Player  0_ago_PPR           0
0        Jeff Smith        0.0   11.672000
1   Henry Ruggs III        0.0   17.511931
2      Jalen Guyton       24.9   12.468000
3          DJ Chark      115.5   40.352000
4       Frank Darby        0.0    1.125867
..              ...        ...         ...
92     Dante Pettis        0.0   28.266000
93    Dezmon Patmon        0.0   15.213000
94   Rashod Bateman       76.5   37.998000
95      Keke Coutee        0.0    1.631010
96    DeVonta Smith      227.6  248.901000

[97 rows x 3 columns]

In [482]:
from sklearn.ensemble import GradientBoostingRegressor

xgb_model = GradientBoostingRegressor(random_state=0)
xgb_model.fit(simplified_X_train, simplified_y_train['0_ago_PPR'])
xgb_model.score(simplified_X_test, simplified_y_test['0_ago_PPR'])

0.6112974359391408

In [483]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(simplified_X_train, simplified_y_train['0_ago_PPR'])
linear_model.score(simplified_X_test, simplified_y_test['0_ago_PPR'])

0.635669519913294

In [484]:
simplified_y_test = simplified_y_test.reset_index()
simplified_y_test = simplified_y_test.drop(['index'], axis=1)
simplified_y_test

             Player  0_ago_PPR
0        Jeff Smith        0.0
1   Henry Ruggs III        0.0
2      Jalen Guyton       24.9
3          DJ Chark      115.5
4       Frank Darby        0.0
..              ...        ...
92     Dante Pettis        0.0
93    Dezmon Patmon        0.0
94   Rashod Bateman       76.5
95      Keke Coutee        0.0
96    DeVonta Smith      227.6

[97 rows x 2 columns]

In [485]:
# y_pred = xgb_model.predict(simplified_X_test)
# y_pred = pd.Series(y_pred)
# comp = pd.concat([simplified_y_test, y_pred], axis=1)
# comp

In [486]:
wr.columns

Index(['Player', 'Age', '0_ago_PPR', '1_ago_G', '1_ago_GS', '1_ago_RushingAtt',
       '1_ago_RushingYds', '1_ago_RushingY/A', '1_ago_RushingTD', '1_ago_Tgt',
       '1_ago_Rec', '1_ago_ReceivingYds', '1_ago_ReceivingY/R',
       '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL', '1_ago_TotalTD',
       '1_ago_PPR', '1_ago_PosRank', '1_ago_year', '1_ago_PPG', '2_ago_G',
       '2_ago_GS', '2_ago_RushingAtt', '2_ago_RushingYds', '2_ago_RushingY/A',
       '2_ago_RushingTD', '2_ago_Tgt', '2_ago_Rec', '2_ago_ReceivingYds',
       '2_ago_ReceivingY/R', '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL',
       '2_ago_TotalTD', '2_ago_PPR', '2_ago_PosRank', '2_ago_year',
       '2_ago_PPG'],
      dtype='object')

In [487]:
final_cols = ['Player', 'Age', 
              '1_ago_G', '1_ago_GS', '1_ago_RushingAtt', '1_ago_RushingYds', '1_ago_RushingY/A', '1_ago_RushingTD', '1_ago_Tgt', '1_ago_Rec', '1_ago_ReceivingYds', 
              '1_ago_ReceivingY/R', '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL', '1_ago_TotalTD', '1_ago_PPR', '1_ago_PosRank', '1_ago_year', '1_ago_PPG',
              '2_ago_G', '2_ago_GS', '2_ago_RushingAtt', '2_ago_RushingYds', '2_ago_RushingY/A', '2_ago_RushingTD', '2_ago_Tgt', '2_ago_Rec', '2_ago_ReceivingYds', 
              '2_ago_ReceivingY/R', '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL', '2_ago_TotalTD', '2_ago_PPR', '2_ago_PosRank', '2_ago_year', '2_ago_PPG'
              ]
wr_pred = pd.DataFrame(columns=final_cols, index=[0])
wr_pred = wr_pred.fillna(0.0)
for player in predicting["Player"].unique():
    individual = predicting[predicting['Player'] == player]
    individual = individual.reset_index()
    data = pd.DataFrame(columns=final_cols, index=[0])
    data['Player'] = player
    data['Age'] = individual.loc[0]['Age']
    for row in individual.itertuples():
        data[str(2025 - row.year) + '_ago_G'] = row.G
        data[str(2025 - row.year) + '_ago_GS'] = row.GS
        data[str(2025 - row.year) + '_ago_RushingAtt'] = row._7
        data[str(2025 - row.year) + '_ago_RushingYds'] = row._8
        data[str(2025 - row.year) + '_ago_RushingY/A'] = row._9
        data[str(2025 - row.year) + '_ago_RushingTD'] = row._10
        data[str(2025 - row.year) + '_ago_Tgt'] = row.Tgt
        data[str(2025 - row.year) + '_ago_Rec'] = row.Rec
        data[str(2025 - row.year) + '_ago_ReceivingYds'] = row._13
        data[str(2025 - row.year) + '_ago_ReceivingY/R'] = row._14
        data[str(2025 - row.year) + '_ago_ReceivingTD'] = row._15
        data[str(2025 - row.year) + '_ago_Fmb'] = row.Fmb
        data[str(2025 - row.year) + '_ago_FL'] = row.FL
        data[str(2025 - row.year) + '_ago_TotalTD'] = row._18
        data[str(2025 - row.year) + '_ago_PPR'] = row.PPR
        data[str(2025 - row.year) + '_ago_PosRank'] = row.PosRank
        data[str(2025 - row.year) + '_ago_PPG'] = row.PPG

    wr_pred = pd.concat([wr_pred, data])

wr_pred.head()

/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  wr_pred = wr_pred.fillna(0.0)
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])
/var/folders/1b/qlbscsf57hngyt99v1b1329c0000gn/T/ipykernel_18948/171959291.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  wr_pred = pd.concat([wr_pred, data])

,Player,Age,1_ago_G,1_ago_GS,1_ago_RushingAtt,1_ago_RushingYds,1_ago_RushingY/A,1_ago_RushingTD,1_ago_Tgt,1_ago_Rec,...,2_ago_ReceivingYds,2_ago_ReceivingY/R,2_ago_ReceivingTD,2_ago_Fmb,2_ago_FL,2_ago_TotalTD,2_ago_PPR,2_ago_PosRank,2_ago_year,2_ago_PPG
0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
0,Ja'Marr Chase,24.0,17.0,16.0,3.0,32.0,10.67,0.0,175.0,127.0,...,1216.0,12.16,7.0,1.0,0.0,7.0,262.7,13.0,NaN,16.41875
0,Justin Jefferson,25.0,17.0,17.0,1.0,3.0,3.00,0.0,154.0,103.0,...,1074.0,15.79,5.0,1.0,1.0,5.0,202.2,26.0,NaN,20.22000
0,Amon-Ra St. Brown,25.0,17.0,17.0,2.0,6.0,3.00,0.0,141.0,115.0,...,1515.0,12.73,10.0,1.0,1.0,10.0,330.9,3.0,NaN,20.68125
0,Brian Thomas,22.0,17.0,16.0,6.0,48.0,8.00,0.0,133.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [488]:
wr_pred = wr_pred.iloc[1:]

In [489]:
wr_pred.columns

Index(['Player', 'Age', '1_ago_G', '1_ago_GS', '1_ago_RushingAtt',
       '1_ago_RushingYds', '1_ago_RushingY/A', '1_ago_RushingTD', '1_ago_Tgt',
       '1_ago_Rec', '1_ago_ReceivingYds', '1_ago_ReceivingY/R',
       '1_ago_ReceivingTD', '1_ago_Fmb', '1_ago_FL', '1_ago_TotalTD',
       '1_ago_PPR', '1_ago_PosRank', '1_ago_year', '1_ago_PPG', '2_ago_G',
       '2_ago_GS', '2_ago_RushingAtt', '2_ago_RushingYds', '2_ago_RushingY/A',
       '2_ago_RushingTD', '2_ago_Tgt', '2_ago_Rec', '2_ago_ReceivingYds',
       '2_ago_ReceivingY/R', '2_ago_ReceivingTD', '2_ago_Fmb', '2_ago_FL',
       '2_ago_TotalTD', '2_ago_PPR', '2_ago_PosRank', '2_ago_year',
       '2_ago_PPG'],
      dtype='object')

In [490]:
wr_pred = wr_pred.fillna(0.0)
wr_pred['Age'] = wr_pred['Age'] + 1
y_2025 = xgb_model.predict(wr_pred[['Age', '1_ago_PPG', '1_ago_PPR', '2_ago_PPG', '2_ago_PPR']])
y_2025 = pd.Series(y_2025, name='2025 PPR Prediction')
wr_pred = wr_pred.reset_index()
wr_pred = wr_pred.drop(['index'], axis=1)
wr_pred

,Player,Age,1_ago_G,1_ago_GS,1_ago_RushingAtt,1_ago_RushingYds,1_ago_RushingY/A,1_ago_RushingTD,1_ago_Tgt,1_ago_Rec,...,2_ago_ReceivingYds,2_ago_ReceivingY/R,2_ago_ReceivingTD,2_ago_Fmb,2_ago_FL,2_ago_TotalTD,2_ago_PPR,2_ago_PosRank,2_ago_year,2_ago_PPG
0,Ja'Marr Chase,25.0,17.0,16.0,3.0,32.0,10.67,0.0,175.0,127.0,...,1216.0,12.16,7.0,1.0,0.0,7.0,262.7,13.0,0.0,16.418750
1,Justin Jefferson,26.0,17.0,17.0,1.0,3.0,3.00,0.0,154.0,103.0,...,1074.0,15.79,5.0,1.0,1.0,5.0,202.2,26.0,0.0,20.220000
2,Amon-Ra St. Brown,26.0,17.0,17.0,2.0,6.0,3.00,0.0,141.0,115.0,...,1515.0,12.73,10.0,1.0,1.0,10.0,330.9,3.0,0.0,20.681250
3,Brian Thomas,23.0,17.0,16.0,6.0,48.0,8.00,0.0,133.0,87.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,Terry McLaurin,30.0,17.0,17.0,2.0,2.0,1.00,0.0,117.0,82.0,...,1002.0,12.68,4.0,0.0,0.0,5.0,209.2,29.0,0.0,12.305882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,Matthew Slater,39.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,233.0,0.0,0.000000
305,Tre'Quan Smith,28.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,234.0,0.0,0.000000
306,Mitchell Tinsley,25.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,235.0,0.0,0.000000
307,Juwann Winfree,28.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,239.0,0.0,0.000000
308,Easop Winston,28.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,240.0,0.0,0.000000

In [491]:
wr_pred = pd.concat([y_2025, wr_pred], axis=1)
wr_pred.head()

,2025 PPR Prediction,Player,Age,1_ago_G,1_ago_GS,1_ago_RushingAtt,1_ago_RushingYds,1_ago_RushingY/A,1_ago_RushingTD,1_ago_Tgt,...,2_ago_ReceivingYds,2_ago_ReceivingY/R,2_ago_ReceivingTD,2_ago_Fmb,2_ago_FL,2_ago_TotalTD,2_ago_PPR,2_ago_PosRank,2_ago_year,2_ago_PPG
0,238.554763,Ja'Marr Chase,25.0,17.0,16.0,3.0,32.0,10.67,0.0,175.0,...,1216.0,12.16,7.0,1.0,0.0,7.0,262.7,13.0,0.0,16.418750
1,259.565648,Justin Jefferson,26.0,17.0,17.0,1.0,3.0,3.00,0.0,154.0,...,1074.0,15.79,5.0,1.0,1.0,5.0,202.2,26.0,0.0,20.220000
2,253.836654,Amon-Ra St. Brown,26.0,17.0,17.0,2.0,6.0,3.00,0.0,141.0,...,1515.0,12.73,10.0,1.0,1.0,10.0,330.9,3.0,0.0,20.681250
3,329.135708,Brian Thomas,23.0,17.0,16.0,6.0,48.0,8.00,0.0,133.0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,266.375723,Terry McLaurin,30.0,17.0,17.0,2.0,2.0,1.00,0.0,117.0,...,1002.0,12.68,4.0,0.0,0.0,5.0,209.2,29.0,0.0,12.305882

In [492]:
wr_pred_view = wr_pred[['2025 PPR Prediction', 'Player']].sort_values('2025 PPR Prediction', ascending=False).reset_index(drop=True)
wr_pred_view.head(10)

   2025 PPR Prediction            Player
0           352.253286      Malik Nabers
1           329.135708      Brian Thomas
2           303.067787       Tee Higgins
3           300.593699      Drake London
4           284.885891     Davante Adams
5           272.931483        Mike Evans
6           270.823315     DeVonta Smith
7           266.375723    Terry McLaurin
8           263.976751     Ladd McConkey
9           259.565648  Justin Jefferson